monolog:
    channels:
        - deprecation
        - chatbot
        - entity

    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event", "!chatbot", "!entity"]
            formatter: monolog.formatter.line

        chatbot:
            type: stream
            path: "%kernel.logs_dir%/chatbot.log"
            level: debug
            channels: ["chatbot"]
            formatter: monolog.formatter.line

        entity:
            type: stream
            path: "%kernel.logs_dir%/entity.log"
            level: debug
            channels: ["entity"]
            formatter: monolog.formatter.line

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event", "!chatbot", "!entity"]
            chatbot:
                type: stream
                path: "%kernel.logs_dir%/chatbot.log"
                level: debug
                channels: ["chatbot"]
            entity:
                type: stream
                path: "%kernel.logs_dir%/entity.log"
                level: debug
                channels: ["entity"]
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event", "!chatbot", "!entity"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
            chatbot:
                type: stream
                path: "%kernel.logs_dir%/chatbot.log"
                level: debug
                channels: ["chatbot"]
            entity:
                type: stream
                path: "%kernel.logs_dir%/entity.log"
                level: debug
                channels: ["entity"]

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50
            nested:
                type: stream
                path: php://stderr
                level: debug
                formatter: monolog.formatter.json
            chatbot:
                type: stream
                path: php://stderr
                level: debug
                channels: ["chatbot"]
                formatter: monolog.formatter.json
            entity:
                type: stream
                path: php://stderr
                level: debug
                channels: ["entity"]
                formatter: monolog.formatter.json
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
            deprecation:
                type: stream
                channels: [deprecation]
                path: php://stderr
                formatter: monolog.formatter.json 